# Generated by Django 4.2.7 on 2023-11-18 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0005_bailiff'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='sygnatura kancelarii')),
                ('type', models.CharField(blank=True, choices=[('eviction', 'eksmisja'), ('payment', 'o zapłatę'), ('divorce', 'rozwód'), ('insolvency', 'zgłoszenie wierzytenlość')], default=None, max_length=60, null=True, verbose_name='typ sprawy')),
                ('result', models.CharField(choices=[('new', 'nowa'), ('begin', 'rozpoczęta'), ('won', 'wygrana'), ('lose', 'przegrana'), ('enforced', 'egzekwowana'), ('end', 'zakończona')], default='new', max_length=60, verbose_name='wynik: sprawy')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='opis')),
                ('bailiff', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subject.bailiff', verbose_name='komornik')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('appears_as', models.CharField(choices=[('plaintiff', 'powód'), ('defendant', 'pozwany')], max_length=14)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='case.case')),
                ('subject', models.ForeignKey(limit_choices_to={'model__in': ['person', 'company']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
