# Generated by Django 4.2.4 on 2023-08-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(default='', max_length=60, verbose_name='ulica')),
                ('house_number', models.CharField(default='', max_length=10, verbose_name='nr. domu / lokalu')),
                ('city', models.CharField(default='Grudziądz', max_length=60, verbose_name='miejscowość')),
                ('postcode', models.CharField(default='86-300', max_length=60, verbose_name='kod pocztowy')),
            ],
        ),
    ]
