# Generated by Django 4.2.4 on 2023-08-14 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(default='', max_length=60, verbose_name='ulica')),
                ('house_number', models.CharField(default='', max_length=10, verbose_name='nr. domu / lokalu')),
                ('city', models.CharField(default='Grudziądz', max_length=60, verbose_name='miejscowość')),
                ('postcode', models.CharField(default='86-300', max_length=60, verbose_name='kod pocztowy')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creating_date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='imię')),
                ('last_name', models.CharField(max_length=60, null=True, verbose_name='nazwisko')),
                ('pesel', models.CharField(blank=True, max_length=11, null=True, verbose_name='numer pesel')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='numer telefonu')),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.adress')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creating_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='pełna nazwa podmiotu gospodarczego')),
                ('nip', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='nip')),
                ('krs', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='notatki')),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.adress')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
