# Generated by Django 4.0.10 on 2023-11-14 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_alter_address_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='adress',
            new_name='address',
        ),
    ]
