# Generated by Django 4.2.7 on 2023-11-18 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_rename_adress_company_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bailiff',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='subject.person')),
                ('office_name', models.CharField(default='', max_length=200, verbose_name='nazwa kancelarii')),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.address')),
            ],
            options={
                'abstract': False,
            },
            bases=('subject.person',),
        ),
    ]
